repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-symlinks
  - id: debug-statements
  - id: end-of-file-fixer
    files: ^(_episodes|README.md|setup.md)
  - id: mixed-line-ending
  - id: trailing-whitespace
    files: ^(_episodes|code|README.md|setup.md)

- repo: https://github.com/asottile/blacken-docs
  rev: "1.13.0"
  hooks:
    - id: blacken-docs
      additional_dependencies: [black==23.3.0]

- repo: https://github.com/codespell-project/codespell
  rev: 'v2.1.0'
  hooks:
  - id: codespell
    types_or: [markdown]
