#------------------------------------------------------------
# Values for this lesson.
#------------------------------------------------------------

# Which carpentry is this (swc, dc, lc, or cp)?
# swc: Software Carpentry
# dc: Data Carpentry
# lc: Library Carpentry
# cp: Carpentries (to use for instructor training for instance)
# incubator: The Carpentries Incubator
# 
# This option supports custom types so lessons can be branded
# and themed with your own logo and alt-text (see `carpentry_description`)
# See https://carpentries.github.io/sandpaper-docs/editing.html#adding-a-custom-logo
carpentry: 'intersect'

# Alt-text description of the lesson.
carpentry_description: 'Packaging'

# Overall title for pages.
title: 'Packaging' # FIXME

# Date the lesson was created (YYYY-MM-DD, this is empty by default)
created: ~ # FIXME

# Comma-separated list of keywords for the lesson
keywords: 'software, data, lesson, The Carpentries' # FIXME

# Life cycle stage of the lesson
# possible values: pre-alpha, alpha, beta, stable
life_cycle: 'beta' # FIXME

# License of the lesson
license: 'CC-BY 4.0'

# Link to the source repository for this lesson
source: 'https://github.com/INTERSECT-training/packaging' # FIXME

# Default branch of your lesson
branch: 'main'

# Who to contact if there are any issues
contact: 'icosden@princeton.edu' # FIXME

# Navigation ------------------------------------------------
#
# Use the following menu items to specify the order of
# individual pages in each dropdown section. Leave blank to
# include all pages in the folder.
#
# Example -------------
#
# episodes:
# - introduction.md
# - first-steps.md
#
# learners:
# - setup.md
#
# instructors:
# - instructor-notes.md
#
# profiles:
# - one-learner.md
# - another-learner.md

# Order of episodes in your lesson
episodes: 
- environment.md
- code-to-package.md
- other-files.md
- metadata.md
- versioning.md
- publishing.md
- documentation.md
- documentation-sphinx.md
- documentation-mkdocs-material.md
- checks.md
- task-runners.md
- continuous-integration.md

# Information for Learners
learners: 
- setup.md

# Information for Instructors
instructors: 
- instructor-notes.md

# Learner Profiles
profiles: 

# Customisation ---------------------------------------------
#
# This space below is where custom yaml items (e.g. pinning
# sandpaper and varnish versions) should live

varnish: intersect-training/varnish
